/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DropFile: typeof import('./components/DropFile.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HeroSection: typeof import('./components/home/HeroSection/index.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowInput: typeof import('./components/Upload/ShowInput.vue')['default']
    ShowResult: typeof import('./components/Upload/ShowResult.vue')['default']
    ToggleLang: typeof import('./components/ToggleLang.vue')['default']
    ToggleTheme: typeof import('./components/ToggleTheme.vue')['default']
    Upload: typeof import('./components/Upload/index.vue')['default']
  }
}
